spring:
  application:
    name: SpringConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sivagandhi1993/SpringConfigServer.git
          search-paths:
            - learn-reactivespring
server:
  port: 8888
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        includes: "*"